config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

   post 'scrap' => 'scrapper#scrap'
   get 'scrap' => 'scrapper#scrap'

end

app/models/store.rb
class Store < ActiveRecord::Base
	def self.save_data page_url
		@store = Store.find_by_url(page_url)
		if @store
			@store.count +=1
	    else
	    	@store = Store.new
	    	@store.url = page_url
		end
		@store.save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/scrapper_controller.rb
class ScrapperController < ApplicationController
  require 'rubygems'
  require 'nokogiri'
  require 'open-uri'

    def scrap
    page_url = params[:site_url]
    doc = Nokogiri::HTML(open(page_url))
    Store.save_data page_url
    @title = doc.at_css("title").text
    @description = doc.at_css("description")
    @images = []
    doc.css("img").each do |item|
      absolute_uri = URI.join( page_url,item[:src]  ).to_s
      @images << absolute_uri
    end
      render :json => { :images =>@images,:title =>@title,:description => @description ,:image_count=> @images.count }.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scrapper_helper.rb
module ScrapperHelper
end

app/views/home/index.html.erb
<%= form_tag(scrap_path,{:method=>"post", remote: true ,:class =>'scraper'}) do %>
  <input type="url" class="focus" placeholder="" name="site_url" >
  <input type="submit" class="btn_submit">
<% end %>


<div class = 'title'></div>
<div class = 'imagecount'></div>
<div class="container">
  <ul class="bxslider" id="slides">

</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageScraper</title>

  <!--<%= javascript_include_tag 'http://code.jquery.com/jquery-1.9.1.min.js', 'data-turbolinks-track' => true %>-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scrapper/scrap.html.erb
<%= @title %>
<%= @description %>
<% @images.each do |image| %>
    <%= image_tag image %>
<% end %>


<div id="container">
  <div id="slides">
    <img src="img/example-slide-1.jpg" alt="Photo by: Missy S Link: http://www.flickr.com/photos/listenmissy/5087404401/">
    <img src="img/example-slide-2.jpg" alt="Photo by: Daniel Parks Link: http://www.flickr.com/photos/parksdh/5227623068/">
    <img src="img/example-slide-3.jpg" alt="Photo by: Mike Ranweiler Link: http://www.flickr.com/photos/27874907@N04/4833059991/">
    <img src="img/example-slide-4.jpg" alt="Photo by: Stuart SeegerLink: http://www.flickr.com/photos/stuseeger/97577796/">
    <a href="#" class="slidesjs-previous slidesjs-navigation"><i class="icon-chevron-left icon-large"></i></a>
    <a href="#" class="slidesjs-next slidesjs-navigation"><i class="icon-chevron-right icon-large"></i></a>
  </div>
</div>